name: Publishing

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: NuGet (Publishing)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Publish to NuGet
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: EliteAPI/EliteAPI.csproj
        PACKAGE_NAME: EliteAPI
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
