name: Publish to NuGet

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to NuGet
    
    steps:
    - uses: actions/checkout@v2

    # Publish to NuGet
    - name: Publish EliteAPI
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: EliteAPI/EliteAPI.csproj
        PACKAGE_NAME: EliteAPI
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
