name: Testing

on:
  push:
    branches: [ master, dev ]

jobs:      
  Events:
    name: Events (Testing)
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Install dependencies
      run: dotnet restore Tests\EliteAPI.Tests.Events
      
    - name: Build
      run: dotnet build Tests\EliteAPI.Tests.Events --configuration Release --no-restore
     
    - name: Test events
      run: Tests\EliteAPI.Tests.Events\bin\Release\netcoreapp3.1\EliteAPI.Tests.Events.exe Journal catalog
    
    - name: Annotations
      uses: yuzutech/annotations-action@v0.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        input: './annotations.json'
      
     
