name: Testing

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:     
  Compiling:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
  Events:
     runs-on: windows-latest

     steps:
     - uses: actions/checkout@v2
        
     - name: Install dependencies
       run: dotnet restore EliteAPI.Tests.Events
      
     - name: Build
       run: dotnet build EliteAPI.Tests.Events --configuration Release --no-restore
     
     - name: Test
       run: bin\Release\netcoreapp3.1\EliteAPI.Tests.Events.exe Journal
       working-directory: EliteAPI.Tests.Events
      
     
