name: Testing

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  Structure:
    runs-on: windows-latest
    steps:
      - run: cmd /c tree
      - run: cmd /c dir
     
  Compiles:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
  Events:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2
     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 3.1.301
        
     - name: Install dependencies
       run: dotnet restore EliteAPI.Tests.Events
      
     - name: Build
       run: dotnet build EliteAPI.Tests.Events --configuration Release --no-restore
     
     - name: Test
       run: EliteAPI.Tests.Events.exe EliteAPI.Tests.Events\Journal
       working-directory: EliteAPI.Tests.Events\bin\Release\netcoreapp3.1
      
     
