name: Testing

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:     
  Compiling:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
  Events:
     runs-on: windows-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v2
        
     - name: Install dependencies
       run: dotnet restore EliteAPI.Tests.Events
      
     - name: Build
       run: dotnet build EliteAPI.Tests.Events --configuration Release --no-restore
     
     - name: Test events
       run: bin\Release\netcoreapp3.1\EliteAPI.Tests.Events.exe Journal
       working-directory: EliteAPI.Tests.Events
    
     - name: Annotations
       uses: Attest/annotations-action@v0.1.0
       with:
        token: ${{ secrets.GITHUB_TOKEN }}
        input: '.bin/Release/netcoreapp3.1/annotations.json'
        title: 'Annotate Files'
        working-directory: EliteAPI.Tests.Events
      
     
